#!/bin/sh

# filesystems
mount -o remount,noatime /
mount -vt efivarfs efivarfs /sys/firmware/efi/efivars -o rw,relatime
mount /dev/nvme0n1p1 /boot
swapon /swapfile

# udevd
udevd --daemon
udevadm trigger --action=add --type=subsystems 
udevadm trigger --action=add --type=devices
udevadm settle

# dbus
install -m755 -g 22 -o 22 -d /run/dbus
dbus-daemon --system --fork --nopidfile

# network
echo localhost > /proc/sys/kernel/hostname
dhcpcd
/usr/libexec/iwd >/dev/null 2>/dev/null &
ip a add 127.0.0.1/8 dev lo
ip link set dev lo up

# bluetooth
/usr/libexec/bluetooth/bluetoothd >/dev/null 2>/dev/null &

# ttys
for i in $(seq 1 12); do
  while :; do
    setsid -c su - root <> /dev/tty$i >&0 2>&1
  done &
done

# init communication
mkdir /run/init
mkfifo /run/init/communication

while :; do
  CMD=`cat /run/init/communication`

  case "$CMD" in
    "reboot" | "poweroff")
      pkill --inverse -f login -15
      sleep 1
      pkill --inverse -f login -9

      sync

      timeout 1 umount -alt nfs
      timeout 1 umount -alt nfs4
      swapoff /swapfile

      for i in /dev/sd?; do
        hd-idle -t $(basename "$i")
      done

      timeout 2 umount -a
      ;;
  esac

  case "$CMD" in
    "reboot")
        echo b > /proc/sysrq-trigger
        cat
        ;;
      "poweroff")
        echo o > /proc/sysrq-trigger
        cat
      ;;
  esac
done >/dev/null 2>/dev/null
