#!/bin/sh

# filesystems
mount -vt efivarfs efivarfs /sys/firmware/efi/efivars -o rw,relatime
mount -t vfat /dev/nvme0n1p1 /boot -o noatime
mount -o remount,noatime /
swapon /swapfile

# udevd
udevd --daemon
udevadm trigger --action=add --type=subsystems 
udevadm trigger --action=add --type=devices
udevadm settle

# dbus
install -m755 -g 22 -o 22 -d /run/dbus
dbus-daemon --system --fork --nopidfile

# network
echo localhost > /proc/sys/kernel/hostname
dhcpcd
/usr/libexec/iwd &> /dev/null &
ip a add 127.0.0.1/8 dev lo
ip link set dev lo up

# bluetooth
/usr/libexec/bluetooth/bluetoothd &> /dev/null &

# ttys
for i in $(seq 1 12); do
	while :; do
		setsid -c su - root <> /dev/tty$i >&0 2>&1
	done &
done

# init communication
mkdir /run/init
mkfifo /run/init/communication

while :; do
  CMD=`cat /run/init/communication`

  if [[ "$CMD" == "poweroff" || "$CMD" == "reboot" ]]; then
    kill -s TERM -1
    sleep 1
    kill -s KILL -1

    sync

    for i in /media/* /mnt/* /boot; do
      timeout 1 umount -R "$i"
    done

    swapoff /swapfile
    mount -o remount,ro /

    for i in /dev/sd?; do
      hd-idle -t $(basename "$i")
    done

    umount -R /dev /sys /run
  fi
  [[ "$CMD" == "poweroff" ]] && echo o > /proc/sysrq-trigger
  [[ "$CMD" == "reboot"   ]] && echo b > /proc/sysrq-trigger
done &> /dev/null
